//go:build e2e || e2e_pkcs11 || e2e_tpm

// Package e2e runs keyroster end to end against real OpenSSH binaries:
// ssh-agent holds the CA key, keyroster-signer issues through its Unix
// socket, and a non-root sshd on 127.0.0.1 decides whether the certificate
// is accepted. ssh-keygen is used as a test oracle only.
//
// Set KEYROSTER_OPENSSH_PREFIX to an OpenSSH install prefix built by
// scripts/build-openssh.sh. The tests fail (never skip) when it is unset.
//
// Later plans add helpers in their own files and do not edit this file
// except where a plan says so.
package e2e

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"
)

// Paths of the binaries built once by TestMain.
var (
	keyrosterBin string
	signerBin    string
)

func TestMain(m *testing.M) {
	os.Exit(runMain(m))
}

func runMain(m *testing.M) int {
	dir, err := os.MkdirTemp("", "keyroster-e2e-bin")
	if err != nil {
		fmt.Fprintln(os.Stderr, "e2e:", err)
		return 1
	}
	defer func() { _ = os.RemoveAll(dir) }()
	root, err := moduleRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "e2e:", err)
		return 1
	}
	keyrosterBin = filepath.Join(dir, "keyroster")
	signerBin = filepath.Join(dir, "keyroster-signer")
	for bin, pkg := range map[string]string{keyrosterBin: "./cmd/keyroster", signerBin: "./cmd/keyroster-signer"} {
		cmd := exec.Command("go", "build", "-trimpath", "-o", bin, pkg)
		cmd.Dir = root
		cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
		if out, err := cmd.CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "e2e: build %s: %v\n%s", pkg, err, out)
			return 1
		}
	}
	return m.Run()
}

func moduleRoot() (string, error) {
	out, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		return "", fmt.Errorf("go env GOMOD: %w", err)
	}
	gomod := strings.TrimSpace(string(out))
	if gomod == "" || gomod == os.DevNull {
		return "", fmt.Errorf("not inside the keyroster module")
	}
	return filepath.Dir(gomod), nil
}

// opensshPrefix returns KEYROSTER_OPENSSH_PREFIX. e2e never skips silently.
func opensshPrefix(t *testing.T) string {
	t.Helper()
	p := os.Getenv("KEYROSTER_OPENSSH_PREFIX")
	if p == "" {
		t.Fatal("KEYROSTER_OPENSSH_PREFIX is not set; build OpenSSH with scripts/build-openssh.sh and point it at the prefix")
	}
	if _, err := os.Stat(filepath.Join(p, "sbin", "sshd")); err != nil {
		t.Fatalf("KEYROSTER_OPENSSH_PREFIX=%s has no sbin/sshd: %v", p, err)
	}
	return p
}

// shortTempDir returns a fresh directory with a short path, for Unix
// sockets (sun_path is limited to 108 bytes).
func shortTempDir(t *testing.T) string {
	t.Helper()
	d, err := os.MkdirTemp("", "kr")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(d) })
	return d
}

// syncBuffer is a goroutine-safe log sink for child processes.
type syncBuffer struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (b *syncBuffer) Write(p []byte) (int, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.Write(p)
}

func (b *syncBuffer) String() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.String()
}

// startDaemon starts a long-running child, stops it with SIGTERM at cleanup
// and dumps its log when the test failed.
func startDaemon(t *testing.T, name string, env []string, bin string, args ...string) (*exec.Cmd, *syncBuffer, <-chan struct{}) {
	t.Helper()
	log := &syncBuffer{}
	cmd := exec.Command(bin, args...)
	cmd.Env = env
	cmd.Stdout = log
	cmd.Stderr = log
	if err := cmd.Start(); err != nil {
		t.Fatalf("start %s: %v", name, err)
	}
	done := make(chan struct{})
	go func() {
		_ = cmd.Wait()
		close(done)
	}()
	t.Cleanup(func() {
		_ = cmd.Process.Signal(syscall.SIGTERM)
		select {
		case <-done:
		case <-time.After(5 * time.Second):
			_ = cmd.Process.Kill()
			<-done
		}
		if t.Failed() {
			t.Logf("--- %s log ---\n%s", name, log.String())
		}
	})
	return cmd, log, done
}

// waitFor polls cond until it holds, the daemon exits, or 15 s pass.
func waitFor(t *testing.T, what string, done <-chan struct{}, log *syncBuffer, cond func() bool) {
	t.Helper()
	deadline := time.Now().Add(15 * time.Second)
	for !cond() {
		select {
		case <-done:
			t.Fatalf("%s: process exited early:\n%s", what, log.String())
		default:
		}
		if time.Now().After(deadline) {
			t.Fatalf("%s: timed out:\n%s", what, log.String())
		}
		time.Sleep(20 * time.Millisecond)
	}
}

func isSocket(path string) bool {
	fi, err := os.Stat(path)
	return err == nil && fi.Mode()&fs.ModeSocket != 0
}

// envWithout returns the current environment minus the named variables.
func envWithout(names ...string) []string {
	var out []string
	for _, kv := range os.Environ() {
		k, _, _ := strings.Cut(kv, "=")
		drop := false
		for _, n := range names {
			if k == n {
				drop = true
			}
		}
		if !drop {
			out = append(out, kv)
		}
	}
	return out
}

// startAgent runs a private ssh-agent and returns its socket path.
func startAgent(t *testing.T) string {
	t.Helper()
	prefix := opensshPrefix(t)
	sock := filepath.Join(shortTempDir(t), "agent.sock")
	_, log, done := startDaemon(t, "ssh-agent", envWithout("SSH_AUTH_SOCK"), filepath.Join(prefix, "bin", "ssh-agent"), "-D", "-a", sock)
	waitFor(t, "ssh-agent socket", done, log, func() bool { return isSocket(sock) })
	return sock
}

// sshKeygen runs the test OpenSSH's ssh-keygen and returns its output.
func sshKeygen(t *testing.T, args ...string) string {
	t.Helper()
	cmd := exec.Command(filepath.Join(opensshPrefix(t), "bin", "ssh-keygen"), args...)
	cmd.Env = envWithout("SSH_AUTH_SOCK")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("ssh-keygen %v: %v\n%s", args, err, out)
	}
	return string(out)
}

// sshAdd loads keyfile into the agent at sock.
func sshAdd(t *testing.T, sock, keyfile string) {
	t.Helper()
	cmd := exec.Command(filepath.Join(opensshPrefix(t), "bin", "ssh-add"), keyfile)
	cmd.Env = append(envWithout("SSH_AUTH_SOCK", "SSH_ASKPASS", "DISPLAY"), "SSH_AUTH_SOCK="+sock)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("ssh-add %s: %v\n%s", keyfile, err, out)
	}
}

// startSigner runs keyroster-signer serve with a fresh 0700 state dir and a
// private socket, plus args, and returns the socket path once it exists.
// A fresh Ed25519 log key is loaded into the agent named by args
// ("--backend-opt socket=...") and pinned with --log-key-fp.
func startSigner(t *testing.T, args ...string) string {
	t.Helper()
	return startSignerProc(t, args...).Socket
}

// signerProc is a running keyroster-signer.
type signerProc struct {
	Socket   string
	StateDir string
	LogPub   string // log public key file (OpenSSH .pub)
	LogFP    string
}

// startSignerProc is startSigner returning the state directory and the log
// key as well.
func startSignerProc(t *testing.T, args ...string) *signerProc {
	t.Helper()
	agentSock := ""
	for i, a := range args {
		if a == "--backend-opt" && i+1 < len(args) && strings.HasPrefix(args[i+1], "socket=") {
			agentSock = strings.TrimPrefix(args[i+1], "socket=")
		}
	}
	if agentSock == "" {
		t.Fatal("startSigner: args name no agent (--backend-opt socket=...)")
	}
	base := shortTempDir(t)
	state := filepath.Join(base, "state")
	if err := os.Mkdir(state, 0o700); err != nil {
		t.Fatal(err)
	}
	logPub, logFP := addLogKey(t, agentSock, base)
	sock := filepath.Join(base, "signer.sock")
	full := append([]string{"serve", "--state-dir", state, "--socket", sock}, args...)
	full = append(full, "--log-key-fp", logFP)
	_, log, done := startDaemon(t, "keyroster-signer", envWithout("SSH_AUTH_SOCK"), signerBin, full...)
	waitFor(t, "signer socket", done, log, func() bool { return isSocket(sock) })
	return &signerProc{Socket: sock, StateDir: state, LogPub: logPub, LogFP: logFP}
}

// addLogKey creates an Ed25519 log key in dir, loads it into the agent at
// agentSock and returns its public key file and fingerprint.
func addLogKey(t *testing.T, agentSock, dir string) (pubFile, fp string) {
	t.Helper()
	key := filepath.Join(dir, "log_key")
	sshKeygen(t, "-q", "-t", "ed25519", "-N", "", "-C", "log-key", "-f", key)
	sshAdd(t, agentSock, key)
	out := sshKeygen(t, "-l", "-E", "sha256", "-f", key+".pub")
	fields := strings.Fields(out)
	if len(fields) < 2 || !strings.HasPrefix(fields[1], "SHA256:") {
		t.Fatalf("ssh-keygen -l: unexpected output %q", out)
	}
	return key + ".pub", fields[1]
}

// sshdOptions configures startSSHD.
type sshdOptions struct {
	UserCAPub  string              // file for TrustedUserCAKeys
	Principals map[string][]string // AuthorizedPrincipalsFile content per user
	Extra      []string            // extra sshd_config lines
}

const sshdConfigTemplate = `Port %d
ListenAddress 127.0.0.1
HostKey %s/ssh_host_ed25519_key
PidFile %s/sshd.pid
StrictModes no
PasswordAuthentication no
KbdInteractiveAuthentication no
AuthorizedKeysFile none
TrustedUserCAKeys %s
AuthorizedPrincipalsFile %s/principals/%%u
LogLevel VERBOSE
`

// startSSHD runs a non-root sshd on 127.0.0.1 and returns its port. The
// config is checked with sshd -t before sshd -D -e starts.
func startSSHD(t *testing.T, opts sshdOptions) int {
	t.Helper()
	prefix := opensshPrefix(t)
	dir := t.TempDir()
	sshKeygen(t, "-q", "-t", "ed25519", "-N", "", "-f", filepath.Join(dir, "ssh_host_ed25519_key"))
	if err := os.Mkdir(filepath.Join(dir, "principals"), 0o755); err != nil {
		t.Fatal(err)
	}
	for u, ps := range opts.Principals {
		if err := os.WriteFile(filepath.Join(dir, "principals", u), []byte(strings.Join(ps, "\n")+"\n"), 0o644); err != nil { //nolint:gosec // test fixture
			t.Fatal(err)
		}
	}
	port := freePort(t)
	cfg := fmt.Sprintf(sshdConfigTemplate, port, dir, dir, opts.UserCAPub, dir)
	for _, l := range opts.Extra {
		cfg += l + "\n"
	}
	cfgPath := filepath.Join(dir, "sshd_config")
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o644); err != nil { //nolint:gosec // test fixture
		t.Fatal(err)
	}
	sshd := filepath.Join(prefix, "sbin", "sshd") // absolute: sshd re-execs itself
	if out, err := exec.Command(sshd, "-t", "-f", cfgPath).CombinedOutput(); err != nil {
		t.Fatalf("sshd -t: %v\n%s\n%s", err, out, cfg)
	}
	_, log, done := startDaemon(t, "sshd", envWithout("SSH_AUTH_SOCK"), sshd, "-D", "-e", "-f", cfgPath)
	waitFor(t, "sshd port", done, log, func() bool {
		c, err := net.DialTimeout("tcp", net.JoinHostPort("127.0.0.1", strconv.Itoa(port)), 200*time.Millisecond)
		if err != nil {
			return false
		}
		_ = c.Close()
		return true
	})
	return port
}

func freePort(t *testing.T) int {
	t.Helper()
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	port := l.Addr().(*net.TCPAddr).Port
	_ = l.Close()
	return port
}

// loginOptions configures sshLogin.
type loginOptions struct {
	Port    int
	Key     string // private key file
	Cert    string // certificate file
	User    string
	Command string
	Extra   []string // extra ssh arguments before the destination
}

// sshLogin runs ssh with a clean client environment (no SSH_AUTH_SOCK, no
// config file, only the given identity) and returns its exit code and
// combined output.
func sshLogin(t *testing.T, opts loginOptions) (int, string) {
	t.Helper()
	args := []string{
		"-F", "none",
		"-i", opts.Key,
		"-o", "CertificateFile=" + opts.Cert,
		"-o", "IdentitiesOnly=yes",
		"-o", "BatchMode=yes",
		"-o", "StrictHostKeyChecking=no",
		"-o", "UserKnownHostsFile=/dev/null",
		"-o", "ConnectTimeout=10",
		"-p", strconv.Itoa(opts.Port),
	}
	args = append(args, opts.Extra...)
	args = append(args, opts.User+"@127.0.0.1", opts.Command)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, filepath.Join(opensshPrefix(t), "bin", "ssh"), args...)
	cmd.Env = envWithout("SSH_AUTH_SOCK")
	out, err := cmd.CombinedOutput()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return ee.ExitCode(), string(out)
		}
		t.Fatalf("ssh: %v\n%s", err, out)
	}
	return 0, string(out)
}

// issue runs keyroster ca issue against the signer socket and fails the
// test when it does not succeed. It returns the combined output.
func issue(t *testing.T, socket string, args ...string) string {
	t.Helper()
	full := append([]string{"ca", "issue", "--socket", socket}, args...)
	cmd := exec.Command(keyrosterBin, full...)
	cmd.Env = envWithout("SSH_AUTH_SOCK")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("keyroster %v: %v\n%s", full, err, out)
	}
	return string(out)
}

// currentUser returns the login name the tests run as; non-root sshd can
// only log in as this user.
func currentUser(t *testing.T) string {
	t.Helper()
	u, err := user.Current()
	if err != nil {
		t.Fatal(err)
	}
	return u.Username
}
